---
settings:
  name: NetApp database solutions
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: true
  pdf:
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-databases.zip
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: 데이터베이스 솔루션
    url: "/index.html"
  - title: 새로운 소식
    url: "/whats-new.html"
  - title: 오라클 데이터베이스
    entries:
    - title: AWS 클라우드
      entries:
      - title: Pacemaker 클러스터링 및 FSx ONTAP 사용한 AWS EC2의 Oracle HA
        pdf-filename: Pacemaker 클러스터링 및 FSx ONTAP 사용한 AWS EC2의 Oracle HA
        url: "/oracle/aws-ora-ha-pacemaker.html"
      - title: iSCSI를 통해 Amazon FSx ONTAP 에서 간소화되고 자동화된 Oracle 배포
        pdf-filename: iSCSI를 통한 Amazon FSx ONTAP 에서의 간소화되고 자동화된 Oracle 배포
        url: "/automation/automation-ora-aws-fsx-iscsi.html"
      - title: 게스트 마운트 FSx ONTAP 사용한 AWS의 VMware Cloud에서 Oracle 사용
        pdf-filename: 게스트 마운트 FSx ONTAP 사용한 AWS의 VMware Cloud에서 Oracle 사용
        url: "/oracle/aws-ora-fsx-vmc-guestmount.html"
      - title: Amazon FSx ONTAP 통한 Oracle Active Data Guard 비용 절감
        pdf-filename: Amazon FSx ONTAP 통한 Oracle Active Data Guard 비용 절감
        url: "/oracle/aws-ora-fsx-ec2-data-guard.html"
      - title: Amazon FSx ONTAP 이용한 Oracle VLDB의 빠른 복구 및 복제
        pdf-filename: Amazon FSx ONTAP 사용한 Oracle VLDB의 빠른 복구 및 복제
        url: "/oracle/aws-ora-fsx-ec2-inc-merge.html"
      - title: NFS/ASM을 사용하여 AWS FSx/EC2에서 독립형 재시작 시 Oracle 19c 사용
        pdf-filename: NFS/ASM을 사용하는 AWS FSx/EC2에서 독립형 재시작을 위한 Oracle 19c
        url: "/oracle/aws-ora-fsx-ec2-nfs-asm.html"
      - title: iSCSI/ASM을 사용한 AWS FSx/EC2에서의 Oracle 데이터베이스 배포 및 보호
        pdf-filename: iSCSI/ASM을 사용한 AWS FSx/EC2에서의 Oracle 데이터베이스 배포 및 보호
        url: "/oracle/aws-ora-fsx-ec2-iscsi-asm.html"
      - title: AWS EC2 및 FSx에 Oracle 데이터베이스 배포 모범 사례
        pdf-filename: AWS EC2 및 FSx에 Oracle 데이터베이스 배포 모범 사례
        entries:
        - title: 사용 사례
          url: "/oracle/aws-ora-fsx-ec2-deploy-intro.html"
        - title: 솔루션 아키텍처
          url: "/oracle/aws-ora-fsx-ec2-architecture.html"
        - title: 고려해야 할 요소
          url: "/oracle/aws-ora-fsx-ec2-factors.html"
        - title: 배포 절차
          url: "/oracle/aws-ora-fsx-ec2-procedures.html"
        - title: 데이터베이스 관리
          url: "/oracle/aws-ora-fsx-ec2-mgmt.html"
        - title: 데이터베이스 마이그레이션
          url: "/oracle/aws-ora-fsx-ec2-migration.html"
    - title: Azure 클라우드
      entries:
      - title: ANF에 대한 고처리량 Oracle VLDB 구현
        pdf-filename: ANF에 대한 고처리량 Oracle VLDB 구현
        url: "/oracle/azure-ora-anf-vldb-dg.html"
      - title: Azure NetApp Files 통한 Oracle Active Data Guard 비용 절감
        pdf-filename: Azure NetApp Files 통한 Oracle Active Data Guard 비용 절감
        url: "/oracle/azure-ora-anf-data-guard.html"
      - title: ANF에서 증분 병합을 통한 Oracle VLDB의 빠른 복구
        pdf-filename: ANF에서 증분 병합을 사용한 Oracle VLDB의 빠른 복구
        url: "/oracle/azure-ora-anf-inc-merge.html"
      - title: NFS를 사용한 Azure NetApp Files 에서의 간소화되고 자동화된 Oracle 배포
        pdf-filename: NFS를 사용한 Azure NetApp Files 에서의 간소화되고 자동화된 Oracle 배포
        url: "/automation/automation-ora-anf-nfs.html"
      - title: ANF를 위한 Oracle 데이터베이스 배포 및 마이그레이션 모범 사례
        pdf-filename: ANF를 위한 Oracle 데이터베이스 배포 및 마이그레이션 모범 사례
        entries:
        - title: 사용 사례
          url: "/oracle/azure-ora-nfile-usecase.html"
        - title: 솔루션 아키텍처
          url: "/oracle/azure-ora-nfile-architecture.html"
        - title: 고려해야 할 요소
          url: "/oracle/azure-ora-nfile-factors.html"
        - title: 배포 절차
          url: "/oracle/azure-ora-nfile-procedures.html"
        - title: 데이터베이스 마이그레이션
          url: "/oracle/azure-ora-nfile-migration.html"
    - title: 구글 클라우드
      entries:
      - title: Google Cloud NetApp Volumes 에서 서버 내 증분 병합을 통해 Oracle VLDB 백업 및 복구 최적화
        pdf-filename: Google Cloud NetApp Volumes 에서 서버 내 증분 병합을 통해 Oracle VLDB 백업
          및 복구 최적화
        url: "/oracle/gcp-ora-gcnv-inc-merge.html"
      - title: Data Guard를 사용한 Google Cloud NetApp Volumes 에서의 고처리량 Oracle VLDB 구현
        pdf-filename: Data Guard를 사용한 GCNV에서의 고처리량 Oracle VLDB 구현
        url: "/oracle/gcp-ora-gcnv-vldb-dg.html"
      - title: '개요: Google Cloud NetApp Volumes 사용한 Oracle 데이터베이스'
        pdf-filename: '개요: Google Cloud NetApp Volumes 사용한 Oracle 데이터베이스'
        url: "/oracle/gcp-oracle-gcnv-overview.html"
    - title: 온프레미스 및 하이브리드 클라우드
      entries:
      - title: vVols 사용한 VCF에서의 Oracle RAC 배포 및 보호
        pdf-filename: vVols 사용한 VCF에서의 Oracle RAC 배포 및 보호
        url: "/oracle/vcf-ora-rac-vvol.html"
      - title: vVols 사용한 VCF에서의 Oracle SI 배포 및 보호
        pdf-filename: vVols 사용한 VCF에서의 Oracle SI 배포 및 보호
        url: "/oracle/vcf-ora-si-vvol.html"
      - title: NFS를 사용한 NetApp C-Series에서의 간소화되고 자동화된 Oracle 배포
        pdf-filename: NFS를 사용한 NetApp C-Series에서의 간소화되고 자동화된 Oracle 배포
        url: "/automation/automation-ora-c-series-nfs.html"
      - title: iSCSI를 통한 NetApp ASA 에서의 간소화되고 자동화된 Oracle 배포
        pdf-filename: iSCSI를 통한 NetApp ASA 에서의 간소화되고 자동화된 Oracle 배포
        url: "/automation/automation-ora-asa-iscsi.html"
      - title: FC를 통한 Cisco UCS 및 NetApp AFF A800 갖춘 FlexPod DataCenter의 Oracle 19c
          RAC 데이터베이스
        pdf-filename: FC를 통한 Cisco UCS 및 NetApp AFF A800 사용한 FlexPod 데이터 센터의 Oracle
          19c RAC 데이터베이스
        url: "/oracle/nva-1155.html"
      - title: UNIX 및 NFS에서 NetApp Clustered Data ONTAP 사용하는 Oracle을 탑재한 SAP
        pdf-filename: UNIX 및 NFS에서 NetApp Clustered Data ONTAP 사용하는 Oracle을 탑재한 SAP
        url: "/oracle/tr-4250.html"
      - title: NFS에서 Oracle 19c for ONTAP 자동 배포
        pdf-filename: NFS에서 Oracle 19c for ONTAP 자동 배포
        entries:
        - title: 개요
          url: "/automation/marketing-overview.html"
        - title: 시작하기 및 요구 사항
          url: "/automation/getting-started-requirements.html"
        - title: 자동화된 Oracle 19c AWX/Tower 배포
          url: "/automation/awx-automation.html"
        - title: 자동화된 Oracle 19c CLI 배포
          url: "/automation/cli-automation.html"
      - title: 자동화된 Oracle 데이터 보호
        pdf-filename: 자동화된 Oracle 데이터 보호
        entries:
        - title: 개요
          url: "/automation/db-protection-overview.html"
        - title: 시작하기 및 요구 사항
          url: "/automation/db-protection-getting-started.html"
        - title: AWX/Tower를 위한 자동화된 Oracle 데이터 보호
          url: "/automation/db-protection-awx-automation.html"
      - title: NetApp EF 시리즈의 Oracle 데이터베이스
        url: "/oracle/tr-4794.html"
  - title: 마이크로소프트 SQL 서버
    entries:
    - title: AWS FSx ONTAP 에서 Microsoft SQL Server 백업 및 복구
      pdf-filename: AWS FSx ONTAP 에서 Microsoft SQL Server 백업 및 복구
      url: "/mssql/sqlsb-backup-restore-aws-fsxn.html"
    - title: Amazon FSx ONTAP 사용한 AWS EC2의 SQL Server
      pdf-filename: Amazon FSx ONTAP 사용한 AWS EC2의 SQL Server
      url: "/mssql/sql-aws-ec2.html"
    - title: Azure NetApp Files 의 SQL Server
      pdf-filename: Azure NetApp Files 의 SQL Server
      entries:
      - title: 개요
        url: "/mssql/sql-srv-anf-overview.html"
      - title: 고려해야 할 요소
        url: "/mssql/sql-srv-anf-factors-to-consider.html"
      - title: 참조 설계(실시간 고수준 설계)
        url: "/mssql/sql-srv-anf-ref-design-overview.html"
      - title: 결론
        url: "/mssql/sql-srv-anf-conclusion.html"
      - title: 추가 정보를 찾을 수 있는 곳
        url: "/mssql/sql-srv-anf-add-info.html"
    - title: Windows에서 Clustered Data ONTAP 사용하는 Microsoft SQL Server가 포함된 SAP
      pdf-filename: Windows에서 Clustered Data ONTAP 사용하여 Microsoft SQL Server와 SAP를
        함께 사용
      url: "/mssql/tr-4467.html"
    - title: Microsoft SQL Server 현대화
      pdf-filename: Microsoft SQL Server 현대화
      url: "/mssql/na-446.html"
    - title: ONTAP 사용한 Microsoft SQL Server 모범 사례 가이드
      pdf-filename: ONTAP 사용한 Microsoft SQL Server 모범 사례 가이드
      url: "/mssql/tr-4590.html"
    - title: NetApp EF-Series를 사용한 Microsoft SQL Server 모범 사례 가이드
      pdf-filename: NetApp EF 시리즈를 사용한 Microsoft SQL Server 모범 사례 가이드
      url: "/mssql/tr-4764.html"
  - title: 오픈 소스 데이터베이스
    entries:
    - title: AWS FSx/EC2에서 자동화된 PostgreSQL HA 배포 및 DR
      pdf-filename: AWS FSx/EC2에서 자동화된 PostgreSQL HA 배포 및 DR
      url: "/postgres/aws-postgres-fsx-ec2-hadr.html"
    - title: NetApp ONTAP 의 MySQL 데이터베이스
      pdf-filename: NetApp ONTAP 의 MySQL 데이터베이스
      url: "/mysql/tr-4722.html"
  - title: 데이터베이스용 SnapCenter
    entries:
    - title: ONTAP 에서의 PostgreSQL 백업, 복구 및 복제
      pdf-filename: ONTAP 에서의 PostgreSQL 백업, 복구 및 복제
      url: "/postgres/snapctr-psql-ontap.html"
    - title: SnapCenter Oracle 클론 수명 주기
      pdf-filename: SnapCenter Oracle 클론 수명 주기
      url: "/automation/automation-ora-clone-lifecycle.html"
    - title: ANF에서의 Oracle 데이터베이스 백업, 복구 및 복제
      pdf-filename: ANF에서의 Oracle 데이터베이스 백업, 복구 및 복제
      url: "/oracle/snapctr-ora-azure-anf.html"
    - title: Oracle용 BlueXP SaaS - Azure
      pdf-filename: Oracle용 BlueXP SaaS - Azure
      url: "/oracle/snapctr-svcs-ora-azure.html"
    - title: Oracle용 BlueXP SaaS - AWS
      pdf-filename: Oracle용 BlueXP SaaS - AWS
      url: "/oracle/snapctr-svcs-ora.html"
    - title: SnapCenter 활용한 하이브리드 클라우드 데이터베이스 솔루션
      pdf-filename: SnapCenter 활용한 하이브리드 클라우드 데이터베이스 솔루션
      entries:
      - title: 소개
        url: "/dbops/hybrid-dbops-snapcenter-usecases.html"
      - title: 솔루션 아키텍처
        url: "/dbops/hybrid-dbops-sc-arch.html"
      - title: 솔루션 요구 사항
        url: "/dbops/hybrid-dbops-sc-requirements.html"
      - title: 필수 구성 요소 구성
        entries:
        - title: 개요
          url: "/dbops/hybrid-dbops-sc-prereq.html"
        - title: 온프레미스 전제 조건
          url: "/dbops/hybrid-dbops-sc-prereq-onprem.html"
        - title: 퍼블릭 클라우드의 전제 조건
          url: "/dbops/hybrid-dbops-sc-prereq-cloud.html"
      - title: 시작하기 개요
        entries:
        - title: 개요
          url: "/dbops/hybrid-dbops-sc-gs.html"
        - title: 온프레미스에서 시작하기
          url: "/dbops/hybrid-dbops-sc-gs-onprem.html"
        - title: AWS 퍼블릭 클라우드 시작하기
          url: "/dbops/hybrid-dbops-sc-gs-aws.html"
      - title: 개발/테스트를 클라우드로 버스팅하기 위한 워크플로
        url: "/dbops/hybrid-dbops-snapcenter-devtest.html"
      - title: 재해 복구 워크플로
        url: "/dbops/hybrid-dbops-snapcenter-dr.html"
  - title: 실제 고객 사례 연구
    entries:
    - title: 의료 제품 회사가 비용 절감을 위해 온프레미스 SQL 워크로드를 Amazon FSx ONTAP 으로 마이그레이션
      url: "/mssql/customer-usecase-mssql-fsx1.html"
  - title: DB 자동화 툴킷
    entries:
    - title: 서버 내 이미지 백업을 통한 자동화된 Oracle VLDB 복제 수명 주기
      url: "/oracle/automation-ora-bkup-clone.html"
    - title: ASM을 사용한 GCNV의 자동화된 Oracle 복제 수명 주기
      url: "/automation/automation-ora-clone-gcnv-asm.html"
    - title: ASM을 사용한 ANF의 자동화된 Oracle 복제 수명 주기
      url: "/automation/automation-ora-clone-anf-asm.html"
    - title: SnapCenter Oracle 복제 수명 주기
      url: "/automation/automation-ora-clone-lifecycle.html"
    - title: Oracle 마이그레이션
      url: "/automation/automation-ora-migration.html"
    - title: AWS FSx ONTAP 활용한 Oracle HA/DR
      url: "/automation/automation-ora-hadr-fsx.html"
    - title: AWS FSx ONTAP 및 EC2 프로비저닝
      url: "/automation/automation-fsx-ec2-provision.html"
  - title: DB 크기 조정 툴킷
    entries:
    - title: ANF에 대한 Oracle 크기 조정 지침
      url: "/oracle/db-sizing-ora-anf.html"
  - title: 비디오
    url: "/videos/index.html"
    entries:
    - title: 오라클 데이터베이스
      url: "/videos/videos-oracle-videos.html"
    - title: 오픈 소스 데이터베이스
      url: "/videos/videos-open-source-videos.html"
    - title: SQL Server 데이터베이스
      url: "/videos/videos-sqlserver-videos.html"
  - title: 블로그
    url: "/blogs.html"
  - title: 법적 고지 사항
    url: "/legal-notices.html"
product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
