---
sidebar: sidebar 
permalink: oracle/aws-ora-fsx-ec2-migration.html 
summary: 이 섹션에서는 온프레미스에서 AWS EC2 인스턴스와 FSx 스토리지로 Oracle 데이터베이스를 마이그레이션할 때 고려해야 할 요소에 대한 자세한 내용을 제공합니다. 
keywords: HA, DR, database, Oracle, RDS, AWS, SnapCenter 
---
= 온프레미스에서 퍼블릭 클라우드로의 데이터베이스 마이그레이션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
데이터베이스 마이그레이션은 어떤 면에서든 어려운 작업입니다.  온프레미스에서 클라우드로 Oracle 데이터베이스를 마이그레이션하는 것도 예외는 아닙니다.

다음 섹션에서는 AWS EC2 컴퓨팅 및 FSx 스토리지 플랫폼을 사용하여 Oracle 데이터베이스를 AWS 퍼블릭 클라우드로 마이그레이션할 때 고려해야 할 주요 요소를 제공합니다.



== ONTAP 스토리지는 온프레미스에서 사용 가능합니다.

온프레미스 Oracle 데이터베이스가 ONTAP 스토리지 어레이에 있는 경우 AWS FSx ONTAP 스토리지에 내장된 NetApp SnapMirror 기술을 사용하여 데이터베이스 마이그레이션을 위한 복제를 설정하는 것이 더 쉽습니다.  NetApp BlueXP 콘솔을 사용하여 마이그레이션 프로세스를 조정할 수 있습니다.

. 온프레미스 인스턴스와 일치하는 대상 컴퓨팅 EC2 인스턴스를 빌드합니다.
. FSx 콘솔에서 동일한 크기의 데이터베이스 볼륨을 제공합니다.
. FSx 데이터베이스 볼륨을 EC2 인스턴스에 마운트합니다.
. 온-프레미스 데이터베이스 볼륨과 대상 FSx 데이터베이스 볼륨 간에 SnapMirror 복제를 설정합니다.  초기 동기화에는 기본 소스 데이터를 이동하는 데 시간이 걸릴 수 있지만, 이후의 증분 업데이트는 훨씬 더 빠르게 진행됩니다.
. 전환 시점에는 기본 애플리케이션을 종료하여 모든 거래를 중단합니다.  Oracle sqlplus CLI 인터페이스에서 Oracle 온라인 로그 스위치를 실행하고 SnapMirror 동기화를 통해 마지막으로 보관된 로그를 대상 볼륨으로 푸시합니다.
. 미러링된 볼륨을 분할하고, 대상에서 Oracle 복구를 실행하고, 서비스를 위해 데이터베이스를 불러옵니다.
. 클라우드의 Oracle 데이터베이스에 애플리케이션을 지정합니다.


다음 비디오에서는 NetApp BlueXP 콘솔과 SnapMirror 복제를 사용하여 온프레미스에서 AWS FSx/EC2로 Oracle 데이터베이스를 마이그레이션하는 방법을 보여줍니다.

.온프레미스 Oracle DB를 AWS로 마이그레이션
video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto]


== ONTAP 스토리지는 온프레미스에서 사용할 수 없습니다.

온프레미스 Oracle 데이터베이스가 ONTAP 아닌 타사 스토리지에 호스팅된 경우 데이터베이스 마이그레이션은 Oracle 데이터베이스 백업 복사본의 복원을 기반으로 합니다.  전환하기 전에 보관 로그를 재생하여 최신 상태로 만들어야 합니다.

AWS S3는 데이터베이스 이동 및 마이그레이션을 위한 스테이징 스토리지 영역으로 사용할 수 있습니다.  이 방법에 대한 다음 상위 단계를 참조하세요.

. 온프레미스 인스턴스와 비슷한 새로운 EC2 인스턴스를 프로비저닝합니다.
. FSx 스토리지에서 동일한 데이터베이스 볼륨을 프로비저닝하고 볼륨을 EC2 인스턴스에 마운트합니다.
. 디스크 수준의 Oracle 백업 복사본을 만듭니다.
. 백업 사본을 AWS S3 스토리지로 이동합니다.
. Oracle 제어 파일을 다시 만들고 S3 스토리지에서 데이터와 보관 로그를 가져와서 데이터베이스를 복원하고 복구합니다.
. 대상 Oracle 데이터베이스를 온프레미스 소스 데이터베이스와 동기화합니다.
. 전환 시, 애플리케이션을 종료하고 Oracle 데이터베이스를 소싱합니다.  마지막 몇 개의 보관 로그를 복사하여 대상 Oracle 데이터베이스에 적용하여 최신 상태로 만듭니다.
. 사용자 액세스를 위해 대상 데이터베이스를 시작합니다.
. 전환을 완료하려면 애플리케이션을 대상 데이터베이스로 리디렉션합니다.




== 최대 가용성을 갖춘 PDB 이전을 사용하여 온프레미스 Oracle 데이터베이스를 AWS FSx/EC2로 마이그레이션합니다.

이 마이그레이션 방식은 이미 PDB/CDB 멀티테넌트 모델에 배포된 Oracle 데이터베이스에 가장 적합하며, ONTAP 스토리지는 온프레미스에서 사용할 수 없습니다.  PDB 이전 방법은 Oracle PDB 핫 클론 기술을 활용하여 서비스 중단을 최소화하면서 소스 CDB와 대상 CDB 간에 PDB를 이동합니다.

먼저 온프레미스에서 마이그레이션할 PDB를 호스팅할 수 있는 충분한 스토리지를 갖춘 AWS FSx/EC2에 CDB를 만듭니다.  온프레미스 PDB 여러 개를 한 번에 하나씩 이전할 수 있습니다.

. 온프레미스 데이터베이스가 다중 테넌트 PDB/CDB 모델이 아닌 단일 인스턴스에 배포된 경우 다음 지침을 따르세요.link:azure-ora-nfile-migration.html#converting-a-single-instance-non-cdb-to-a-pdb-in-a-multitenant-cdb["다중 테넌트 CDB의 단일 인스턴스 비CDB를 PDB로 변환"^] 단일 인스턴스를 멀티테넌트 PDB/CDB로 변환합니다.  그런 다음 다음 단계에 따라 변환된 PDB를 AWS FSx/EC2의 CDB로 마이그레이션합니다.
. 온프레미스 데이터베이스가 이미 멀티테넌트 PDB/CDB 모델에 배포된 경우 다음 지침을 따르세요.link:azure-ora-nfile-migration.html#migrate-on-premises-oracle-databases-to-azure-with-pdb-relocation["PDB 이전을 통해 온프레미스 Oracle 데이터베이스를 클라우드로 마이그레이션"^] 마이그레이션을 수행합니다.


다음 비디오에서는 PDB 재배치를 사용하여 최대 가용성으로 Oracle 데이터베이스(PDB)를 FSx/EC2로 마이그레이션하는 방법을 보여줍니다.

link:https://www.netapp.tv/insight/details/29998?playlist_id=0&mcid=85384745435828386870393606008847491796["최대 가용성으로 온프레미스 Oracle PDB를 AWS CDB로 마이그레이션"^]


NOTE: 1단계와 2단계의 지침은 Azure 퍼블릭 클라우드를 기준으로 설명되어 있지만, 해당 절차는 아무런 변경 없이 AWS 클라우드에도 적용할 수 있습니다.

NetApp Solutions Automation 팀은 온프레미스에서 AWS 클라우드로 Oracle 데이터베이스를 마이그레이션하는 데 도움이 되는 마이그레이션 툴킷을 제공합니다.  다음 명령을 사용하여 PDB 이전을 위한 Oracle 데이터베이스 마이그레이션 툴킷을 다운로드합니다.

[source, cli]
----
git clone https://github.com/NetApp-Automation/na_ora_aws_migration.git
----