---
sidebar: sidebar 
permalink: oracle/azure-ora-nfile-usecase.html 
summary: 이 모범 사례 가이드에서는 Azure NetApp 파일 저장소와 Azure VM에 Oracle 데이터베이스를 배포하고 마이그레이션하기 위한 솔루션에 대한 자세한 내용을 제공합니다. 
keywords: database, Oracle, Azure NetApp files, Azure 
---
= TR-4954: ANF를 위한 Oracle 데이터베이스 배포 및 마이그레이션 모범 사례
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 모범 사례 가이드에서는 Azure NetApp 파일 저장소와 Azure VM에 Oracle 데이터베이스를 배포하고 마이그레이션하기 위한 솔루션에 대한 자세한 내용을 제공합니다.



== 개요

많은 미션 크리티컬 Oracle 엔터프라이즈 데이터베이스는 여전히 온프레미스에서 호스팅되고 있으며, 많은 기업이 이러한 Oracle 데이터베이스를 퍼블릭 클라우드로 마이그레이션하려고 합니다.  종종 이러한 Oracle 데이터베이스는 애플리케이션 중심적이어서 사용자별 구성이 필요한데, 이 기능은 많은 데이터베이스 즉 서비스형 퍼블릭 클라우드 서비스에서 누락되어 있습니다.  따라서 현재의 데이터베이스 환경에서는 고유한 요구 사항을 수용할 수 있는 고성능, 확장 가능한 컴퓨팅 및 스토리지 서비스를 기반으로 구축된 퍼블릭 클라우드 기반 Oracle 데이터베이스 솔루션이 필요합니다.  Azure 가상 머신 컴퓨팅 인스턴스와 Azure NetApp Files 스토리지 서비스는 미션 크리티컬 Oracle 데이터베이스 워크로드를 퍼블릭 클라우드로 구축하고 마이그레이션하는 데 활용할 수 있는 퍼즐의 잃어버린 조각일 수 있습니다.



== Azure 가상 머신

Azure 가상 머신은 Azure가 제공하는 여러 유형의 주문형 확장 가능 컴퓨팅 리소스 중 하나입니다.  일반적으로 컴퓨팅 환경에 대한 다른 선택 사항보다 더 많은 제어가 필요할 때 가상 머신을 선택합니다.  Azure 가상 머신은 컴퓨팅 또는 메모리 집약적 워크로드를 위한 것이든, Oracle 데이터베이스를 실행하는 데 필요한 특정 구성을 갖춘 컴퓨터를 빠르고 쉽게 만들 수 있는 방법을 제공합니다.  Azure 가상 네트워크의 가상 머신은 보안된 VPN 터널 등을 통해 조직의 네트워크에 쉽게 연결할 수 있습니다.



== Azure NetApp Files (ANF)

Azure NetApp Files 이전보다 더 빠르고 안전하게 데이터베이스 워크로드를 클라우드로 이전하는 완벽하게 관리되는 Microsoft 서비스입니다.  이 솔루션은 클라우드에서 Oracle 데이터베이스와 같은 고성능 워크로드를 실행하는 데 필요한 핵심 요구 사항을 충족하도록 설계되었으며, 실제 IOPS 요구 사항 범위, 낮은 지연 시간, 높은 가용성, 높은 내구성, 대규모 관리 용이성, 빠르고 효율적인 백업, 복구 및 복제를 반영하는 성능 계층을 제공합니다.  이러한 기능은 Azure NetApp Files Azure 데이터 센터 환경 내에서 실행되는 물리적 올플래시 NetApp ONTAP 시스템을 기반으로 하기 때문에 가능합니다.  Azure NetApp Files Azure DC 및 포털에 완벽하게 통합되어 있으며, 고객은 다른 Azure 개체와 마찬가지로 편리한 그래픽 인터페이스와 API를 사용하여 공유 파일을 만들고 관리할 수 있습니다.  Azure NetApp File을 사용하면 추가적인 위험, 비용 또는 시간 없이 Azure의 모든 기능을 활용할 수 있으며 Azure에서 기본적으로 제공되는 유일한 엔터프라이즈 파일 서비스를 신뢰할 수 있습니다.



== 결론

이 문서에서는 온-프레미스 시스템과 유사한 성능과 내구성을 제공하는 Azure 가상 머신과 Azure NetApp Files 스토리지 서비스를 사용하여 Oracle 데이터베이스를 배포, 구성 및 마이그레이션하는 방법을 자세히 설명합니다.  모범 사례 지침은 TR-4780을 참조하세요.link:https://www.netapp.com/media/17105-tr4780.pdf["Microsoft Azure의 Oracle 데이터베이스"^] .  더 중요한 점은 NetApp Azure 퍼블릭 클라우드에서 Oracle 데이터베이스 워크로드의 배포, 구성, 데이터 보호, 마이그레이션 및 관리에 필요한 대부분의 작업을 자동화하는 자동화 툴킷을 제공한다는 것입니다.  자동화 툴킷은 NetApp 공개 GitHub 사이트에서 다운로드할 수 있습니다.link:https://github.com/NetApp-Automation/["NetApp 자동화"^] .
