---
sidebar: sidebar 
permalink: dbops/hybrid-dbops-sc-prereq-cloud.html 
summary: Cloud Manager 커넥터와 Cloud Volumes ONTAP 설치하고 SnapMirror 구성하기 전에 클라우드 환경에 대한 몇 가지 준비를 수행해야 합니다.  이 페이지에서는 Cloud Volumes ONTAP 배포할 때 수행해야 할 작업과 고려 사항을 설명합니다. 
keywords: prerequisites, aws, azure, gcp, cloud central, cloud volumes ontap 
---
= 퍼블릭 클라우드의 전제 조건
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cloud Manager 커넥터와 Cloud Volumes ONTAP 설치하고 SnapMirror 구성하기 전에 클라우드 환경에 대한 몇 가지 준비를 수행해야 합니다.  이 페이지에서는 Cloud Volumes ONTAP 배포할 때 수행해야 할 작업과 고려 사항을 설명합니다.



== Cloud Manager 및 Cloud Volumes ONTAP 배포 필수 조건 체크리스트

* NetApp Cloud Central 로그인
* 웹 브라우저에서 여러 엔드포인트로의 네트워크 액세스
* 커넥터의 네트워크 위치
* 클라우드 공급자 권한
* 개별 서비스를 위한 네트워킹


시작하는 데 필요한 사항에 대한 자세한 내용은 당사를 방문하세요. https://docs.netapp.com/us-en/occm/reference_checklist_cm.html["클라우드 문서"^] .



== 고려 사항



=== 1. Cloud Manager 커넥터란 무엇인가요?

대부분의 경우 Cloud Central 계정 관리자는 클라우드 또는 온프레미스 네트워크에 커넥터를 배포해야 합니다.  이 커넥터를 사용하면 Cloud Manager가 퍼블릭 클라우드 환경 내의 리소스와 프로세스를 관리할 수 있습니다.

커넥터에 대한 자세한 내용은 당사를 방문하세요. https://docs.netapp.com/us-en/occm/concept_connectors.html["클라우드 문서"^] .



=== 2. Cloud Volumes ONTAP 크기 조정 및 아키텍처

Cloud Volumes ONTAP 배포할 때 미리 정의된 패키지를 선택하거나 직접 구성을 만들 수 있습니다.  이러한 값 중 다수는 나중에 중단 없이 변경할 수 있지만 클라우드에 배포할 작업 부하에 따라 배포 전에 내려야 할 몇 가지 주요 결정이 있습니다.

각 클라우드 제공업체는 배포 옵션이 서로 다르며, 거의 모든 작업 부하에는 고유한 속성이 있습니다.  NetApp 에는 https://bluexp.netapp.com/calculator-hub["TCO 계산기"^] 용량과 성능에 따라 배포 크기를 올바르게 조정하는 데 도움이 될 수 있지만 고려할 가치가 있는 몇 가지 기본 개념을 중심으로 구축되었습니다.

* 필요한 용량
* 클라우드 가상 머신의 네트워크 기능
* 클라우드 스토리지의 성능 특성


핵심은 현재의 용량 및 성능 요구 사항을 충족할 뿐만 아니라 향후 성장까지 고려한 구성을 계획하는 것입니다.  이는 일반적으로 용량 헤드룸과 성능 헤드룸으로 알려져 있습니다.

추가 정보가 필요하면 올바른 계획에 대한 설명서를 읽어보세요. https://docs.netapp.com/us-en/occm/task_planning_your_config.html["AWS"^] , https://docs.netapp.com/us-en/occm/task_planning_your_config_azure.html["하늘빛"^] , 그리고 https://docs.netapp.com/us-en/occm/task_planning_your_config_gcp.html["지씨피"^] .



=== 3. 단일 노드 또는 고가용성?

모든 클라우드에는 단일 노드 또는 두 개의 노드가 있는 클러스터형 고가용성 쌍에 CVO를 배포하는 옵션이 있습니다.  사용 사례에 따라 비용 절감을 위해 단일 노드를 배포하거나, 가용성과 중복성을 높이기 위해 HA 쌍을 배포할 수 있습니다.

재해 복구 사용 사례나 개발 및 테스트를 위한 임시 스토리지 구축의 경우, 갑작스러운 영역 또는 인프라 중단의 영향이 적기 때문에 단일 노드가 일반적입니다.  그러나 데이터가 단일 위치에만 있거나 데이터 세트에 더 많은 중복성과 가용성이 필요한 모든 프로덕션 사용 사례에서는 높은 가용성이 권장됩니다.

각 클라우드의 고가용성 버전 아키텍처에 대한 자세한 내용은 다음 문서를 참조하세요. https://docs.netapp.com/us-en/occm/concept_ha.html["AWS"^] , https://docs.netapp.com/us-en/occm/concept_ha_azure.html["하늘빛"^] 그리고 https://docs.netapp.com/us-en/occm/concept_ha_google_cloud.html["지씨피"^] .
