---
sidebar: sidebar 
permalink: automation/awx-automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 이 페이지에서는 NetApp ONTAP 스토리지에 Oracle19c를 배포하는 자동화된 방법을 설명합니다. 
---
= 단계별 배포 절차
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 페이지에서는 NetApp ONTAP 스토리지에 Oracle19c를 배포하는 자동화된 방법을 설명합니다.



== AWX/Tower 배포 Oracle 19c 데이터베이스



=== 1. 사용자 환경에 대한 인벤토리, 그룹, 호스트 및 자격 증명을 만듭니다.

이 섹션에서는 NetApp 자동화 솔루션을 사용하기 위한 환경을 준비하는 AWX/Ansible Tower에서 인벤토리, 그룹, 호스트 및 액세스 자격 증명을 설정하는 방법을 설명합니다.

. 인벤토리를 구성합니다.
+
.. 리소스 → 인벤토리 → 추가로 이동한 후 인벤토리 추가를 클릭합니다.
.. 이름과 조직 세부 정보를 입력하고 '저장'을 클릭합니다.
.. 인벤토리 페이지에서 생성된 인벤토리를 클릭합니다.
.. 재고 변수가 있으면 변수 필드에 붙여넣습니다.
.. 그룹 하위 메뉴로 이동하여 추가를 클릭합니다.
.. ONTAP 에 대한 그룹 이름을 제공하고, 그룹 변수(있는 경우)를 붙여넣은 다음 저장을 클릭합니다.
.. 다른 Oracle 그룹에 대해서도 이 과정을 반복합니다.
.. 생성된 ONTAP 그룹을 선택하고 호스트 하위 메뉴로 이동하여 새 호스트 추가를 클릭합니다.
.. ONTAP 클러스터 관리 IP의 IP 주소를 제공하고 호스트 변수(있는 경우)를 붙여넣은 다음 저장을 클릭합니다.
.. Oracle 그룹 및 Oracle 호스트 관리 IP/호스트 이름에 대해 이 프로세스를 반복해야 합니다.


. 자격 증명 유형을 만듭니다. ONTAP 과 관련된 솔루션의 경우 사용자 이름 및 비밀번호 항목과 일치하도록 자격 증명 유형을 구성해야 합니다.
+
.. 관리 → 자격 증명 유형으로 이동한 다음 추가를 클릭합니다.
.. 이름과 설명을 입력하세요.
.. 다음 내용을 입력 구성에 붙여넣으세요.




[source, cli]
----
fields:
  - id: username
    type: string
    label: Username
  - id: password
    type: string
    label: Password
    secret: true
  - id: vsadmin_password
    type: string
    label: vsadmin_password
    secret: true
----
. 다음 내용을 Injector Configuration에 붙여넣습니다.


[source, cli]
----
extra_vars:
  password: '{{ password }}'
  username: '{{ username }}'
  vsadmin_password: '{{ vsadmin_password }}'
----
. 자격 증명을 구성합니다.
+
.. 리소스 → 자격 증명으로 이동한 다음 추가를 클릭합니다.
.. ONTAP 의 이름과 조직 세부 정보를 입력하세요.
.. ONTAP 에 대해 생성한 사용자 정의 자격 증명 유형을 선택합니다.
.. 유형 세부 정보에서 사용자 이름, 비밀번호, vsadmin_password를 입력합니다.
.. 자격 증명으로 돌아가기를 클릭하고 추가를 클릭합니다.
.. Oracle의 이름과 조직 세부 정보를 입력하세요.
.. 머신 자격 증명 유형을 선택하세요.
.. 유형 세부 정보에서 Oracle 호스트의 사용자 이름과 비밀번호를 입력합니다.
.. 올바른 권한 상승 방법을 선택하고 사용자 이름과 비밀번호를 입력하세요.






=== 2. 프로젝트 만들기

. 리소스 → 프로젝트로 가서 추가를 클릭합니다.
+
.. 이름과 조직 세부정보를 입력하세요.
.. 소스 제어 자격 증명 유형 필드에서 Git을 선택합니다.
.. 입력하다 `\https://github.com/NetApp-Automation/na_oracle19c_deploy.git` 소스 제어 URL로.
.. Save를 클릭합니다.
.. 소스 코드가 변경되면 프로젝트를 가끔씩 동기화해야 할 수도 있습니다.






=== 3. Oracle host_vars 구성

이 섹션에 정의된 변수는 각 Oracle 서버와 데이터베이스에 적용됩니다.

. 다음의 내장된 Oracle 호스트 변수나 host_vars 형식으로 환경별 매개변수를 입력하세요.



NOTE: 파란색 항목은 환경에 맞게 변경해야 합니다.



=== 호스트 VARS 구성

[source, shell]
----
######################################################################
##############      Host Variables Configuration        ##############
######################################################################

# Add your Oracle Host
ansible_host: "10.61.180.15"

# Oracle db log archive mode: true - ARCHIVELOG or false - NOARCHIVELOG
log_archive_mode: "true"

# Number of pluggable databases per container instance identified by sid. Pdb_name specifies the prefix for container database naming in this case cdb2_pdb1, cdb2_pdb2, cdb2_pdb3
oracle_sid: "cdb2"
pdb_num: "3"
pdb_name: "{{ oracle_sid }}_pdb"

# CDB listener port, use different listener port for additional CDB on same host
listener_port: "1523"

# CDB is created with SGA at 75% of memory_limit, MB. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB. The grand total SGA should not exceed 75% available RAM on node.
memory_limit: "5464"

# Set "em_configuration: DBEXPRESS" to install enterprise manager express and choose a unique port from 5500 to 5599 for each sid on the host.
# Leave them black if em express is not installed.
em_configuration: "DBEXPRESS"
em_express_port: "5501"

# {{groups.oracle[0]}} represents first Oracle DB server as defined in Oracle hosts group [oracle]. For concurrent multiple Oracle DB servers deployment, [0] will be incremented for each additional DB server. For example,  {{groups.oracle[1]}}" represents DB server 2, "{{groups.oracle[2]}}" represents DB server 3 ... As a good practice and the default, minimum three volumes is allocated to a DB server with corresponding /u01, /u02, /u03 mount points, which store oracle binary, oracle data, and oracle recovery files respectively. Additional volumes can be added by click on "More NFS volumes" but the number of volumes allocated to a DB server must match with what is defined in global vars file by volumes_nfs parameter, which dictates how many volumes are to be created for each DB server.
host_datastores_nfs:
  - {vol_name: "{{groups.oracle[0]}}_u01", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u02", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u03", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
----
. 파란색 필드에 모든 변수를 입력하세요.
. 변수 입력을 완료한 후, 양식에서 복사 버튼을 클릭하면 AWX나 Tower로 전송할 모든 변수가 복사됩니다.
. AWX 또는 Tower로 돌아가서 리소스 → 호스트로 이동한 다음 Oracle 서버 구성 페이지를 선택하여 엽니다.
. 세부 정보 탭에서 편집을 클릭하고 1단계에서 복사한 변수를 YAML 탭 아래의 변수 필드에 붙여넣습니다.
. Save를 클릭합니다.
. 시스템의 추가 Oracle 서버에 대해 이 과정을 반복합니다.




=== 4. 전역 변수 구성

이 섹션에 정의된 변수는 모든 Oracle 호스트, 데이터베이스 및 ONTAP 클러스터에 적용됩니다.

. 다음의 내장된 전역 변수나 vars 형태로 환경별 매개변수를 입력합니다.



NOTE: 파란색 항목은 환경에 맞게 변경해야 합니다.

[source, shell]
----
#######################################################################
###### Oracle 19c deployment global user configuration variables ######
######  Consolidate all variables from ontap, linux and oracle   ######
#######################################################################

###########################################
### Ontap env specific config variables ###
###########################################

#Inventory group name
#Default inventory group name - 'ontap'
#Change only if you are changing the group name either in inventory/hosts file or in inventory groups in case of AWX/Tower
hosts_group: "ontap"

#CA_signed_certificates (ONLY CHANGE to 'true' IF YOU ARE USING CA SIGNED CERTIFICATES)
ca_signed_certs: "false"

#Names of the Nodes in the ONTAP Cluster
nodes:
 - "AFF-01"
 - "AFF-02"

#Storage VLANs
#Add additional rows for vlans as necessary
storage_vlans:
   - {vlan_id: "203", name: "infra_NFS", protocol: "NFS"}
More Storage VLANsEnter Storage VLANs details

#Details of the Data Aggregates that need to be created
#If Aggregate creation takes longer, subsequent tasks of creating volumes may fail.
#There should be enough disks already zeroed in the cluster, otherwise aggregate create will zero the disks and will take long time
data_aggregates:
  - {aggr_name: "aggr01_node01"}
  - {aggr_name: "aggr01_node02"}

#SVM name
svm_name: "ora_svm"

# SVM Management LIF Details
svm_mgmt_details:
  - {address: "172.21.91.100", netmask: "255.255.255.0", home_port: "e0M"}

# NFS storage parameters when data_protocol set to NFS. Volume named after Oracle hosts name identified by mount point as follow for oracle DB server 1. Each mount point dedicates to a particular Oracle files: u01 - Oracle binary, u02 - Oracle data, u03 - Oracle redo. Add additional volumes by click on "More NFS volumes" and also add the volumes list to corresponding host_vars as host_datastores_nfs variable. For multiple DB server deployment, additional volumes sets needs to be added for additional DB server. Input variable "{{groups.oracle[1]}}_u01", "{{groups.oracle[1]}}_u02", and "{{groups.oracle[1]}}_u03" as vol_name for second DB server. Place volumes for multiple DB servers alternatingly between controllers for balanced IO performance, e.g. DB server 1 on controller node1, DB server 2 on controller node2 etc. Make sure match lif address with controller node.

volumes_nfs:
  - {vol_name: "{{groups.oracle[0]}}_u01", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u02", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u03", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}

#NFS LIFs IP address and netmask

nfs_lifs_details:
  - address: "172.21.94.200" #for node-1
    netmask: "255.255.255.0"
  - address: "172.21.94.201" #for node-2
    netmask: "255.255.255.0"

#NFS client match

client_match: "172.21.94.0/24"

###########################################
### Linux env specific config variables ###
###########################################

#NFS Mount points for Oracle DB volumes

mount_points:
  - "/u01"
  - "/u02"
  - "/u03"

# Up to 75% of node memory size divided by 2mb. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB.
# Leave it blank if hugepage is not configured on the host.

hugepages_nr: "1234"

# RedHat subscription username and password

redhat_sub_username: "xxx"
redhat_sub_password: "xxx"

####################################################
### DB env specific install and config variables ###
####################################################

db_domain: "your.domain.com"

# Set initial password for all required Oracle passwords. Change them after installation.

initial_pwd_all: "netapp123"
----
. 모든 변수를 파란색 필드에 입력하세요.
. 변수 입력을 완료한 후, 양식에서 복사 버튼을 클릭하면 AWX 또는 Tower로 전송할 모든 변수가 다음 작업 템플릿으로 복사됩니다.




=== 5. 작업 템플릿을 구성하고 시작합니다.

. 작업 템플릿을 만듭니다.
+
.. 리소스 → 템플릿 → 추가로 이동하여 작업 템플릿 추가를 클릭합니다.
.. 이름과 설명을 입력하세요
.. 작업 유형을 선택합니다. 실행은 플레이북을 기반으로 시스템을 구성하고, 확인은 실제로 시스템을 구성하지 않고 플레이북의 테스트 실행을 수행합니다.
.. 플레이북에 해당하는 인벤토리, 프로젝트, 플레이북 및 자격 증명을 선택합니다.
.. 실행할 기본 플레이북으로 all_playbook.yml을 선택합니다.
.. 4단계에서 복사한 전역 변수를 YAML 탭의 템플릿 변수 필드에 붙여넣습니다.
.. 작업 태그 필드에서 시작 시 프롬프트 상자를 체크합니다.
.. Save를 클릭합니다.


. 작업 템플릿을 실행합니다.
+
.. 리소스 → 템플릿으로 이동합니다.
.. 원하는 템플릿을 클릭한 다음 실행을 클릭합니다.
.. 작업 태그를 입력하라는 메시지가 표시되면 requirements_config를 입력합니다.  requirements_config 아래의 '직무 태그 생성' 줄을 클릭해서 직무 태그를 입력해야 할 수도 있습니다.





NOTE: requirements_config는 다른 역할을 실행하는 데 필요한 올바른 라이브러리가 있는지 확인합니다.

. 다음을 클릭한 다음 실행을 클릭하여 작업을 시작합니다.
. 보기 → 작업을 클릭하여 작업 출력과 진행 상황을 모니터링합니다.
. 작업 태그를 입력하라는 메시지가 표시되면 ontap_config를 입력합니다.  ontap_config 바로 아래에 있는 "작업 태그" 줄 만들기를 클릭해서 작업 태그를 입력해야 할 수도 있습니다.
. 다음을 클릭한 다음 실행을 클릭하여 작업을 시작합니다.
. 보기 → 작업을 클릭하여 작업 출력 및 진행 상황을 모니터링합니다.
. ontap_config 역할이 완료된 후 linux_config에 대해 프로세스를 다시 실행합니다.
. 리소스 → 템플릿으로 이동합니다.
. 원하는 템플릿을 선택한 다음 실행을 클릭합니다.
. linux_config에서 작업 태그 유형을 묻는 메시지가 나타나면 linux_config 바로 아래에 있는 "작업 태그" 줄 만들기를 선택하여 작업 태그를 입력해야 할 수도 있습니다.
. 다음을 클릭한 다음 실행을 클릭하여 작업을 시작합니다.
. 보기 → 작업을 선택하여 작업 출력과 진행 상황을 모니터링합니다.
. linux_config 역할이 완료된 후 oracle_config에 대해 프로세스를 다시 실행합니다.
. 리소스 → 템플릿으로 이동합니다.
. 원하는 템플릿을 선택한 다음 실행을 클릭합니다.
. 작업 태그를 입력하라는 메시지가 표시되면 oracle_config를 입력합니다.  oracle_config 바로 아래에 있는 "작업 태그" 줄을 선택하여 작업 태그를 입력해야 할 수도 있습니다.
. 다음을 클릭한 다음 실행을 클릭하여 작업을 시작합니다.
. 보기 → 작업을 선택하여 작업 출력과 진행 상황을 모니터링합니다.




=== 6. 동일한 Oracle 호스트에 추가 데이터베이스 배포

플레이북의 Oracle 부분은 실행 당 Oracle 서버에 단일 Oracle 컨테이너 데이터베이스를 생성합니다.  동일한 서버에 추가 컨테이너 데이터베이스를 만들려면 다음 단계를 완료하세요.

. host_vars 변수를 수정합니다.
+
.. 2단계 - Oracle host_vars 구성으로 돌아갑니다.
.. Oracle SID를 다른 명명 문자열로 변경합니다.
.. 리스너 포트를 다른 번호로 변경합니다.
.. EM Express를 설치하는 경우 EM Express 포트를 다른 번호로 변경하세요.
.. 수정된 호스트 변수를 복사하여 호스트 구성 세부 정보 탭의 Oracle 호스트 변수 필드에 붙여넣습니다.


. oracle_config 태그만 사용하여 배포 작업 템플릿을 시작합니다.
. Oracle 사용자로 Oracle 서버에 로그인하고 다음 명령을 실행합니다.
+
[source, cli]
----
ps -ef | grep ora
----
+

NOTE: 예상대로 설치가 완료되고 Oracle DB가 시작되면 Oracle 프로세스가 나열됩니다.

. 데이터베이스에 로그인하여 다음 명령 세트로 생성된 db 구성 설정과 PDB를 확인하세요.
+
[source, cli]
----
[oracle@localhost ~]$ sqlplus / as sysdba

SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 12:52:51 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0

SQL>

SQL> select name, log_mode from v$database;
NAME      LOG_MODE
--------- ------------
CDB2      ARCHIVELOG

SQL> show pdbs

    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO

col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;

SQL> col svrname form a30
SQL> col dirname form a30
SQL> select svrname, dirname, nfsversion from v$dnfs_servers;

SVRNAME                        DIRNAME                        NFSVERSION
------------------------------ ------------------------------ ----------------
172.21.126.200                 /rhelora03_u02                 NFSv3.0
172.21.126.200                 /rhelora03_u03                 NFSv3.0
172.21.126.200                 /rhelora03_u01                 NFSv3.0
----
+
이는 dNFS가 제대로 작동하고 있음을 확인합니다.

. 다음 명령을 사용하여 리스너를 통해 데이터베이스에 연결하여 Oracle 리스너 구성을 확인합니다.  적절한 리스너 포트와 데이터베이스 서비스 이름으로 변경합니다.
+
[source, cli]
----
[oracle@localhost ~]$ sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com

SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 13:19:57 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Wed May 05 2021 17:11:11 -04:00

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0

SQL> show user
USER is "SYSTEM"
SQL> show con_name
CON_NAME
CDB2_PDB1
----
+
이는 Oracle 리스너가 제대로 작동하고 있음을 확인합니다.





=== 도움을 받으려면 어디로 가야 하나요?

툴킷 사용에 도움이 필요하면 가입하세요.link:https://netapppub.slack.com/archives/C021R4WC0LC["NetApp 솔루션 자동화 커뮤니티 지원 슬랙 채널"] 질문이나 문의사항이 있으면 솔루션 자동화 채널을 찾아 게시하세요.
