---
sidebar: sidebar 
permalink: automation/db-protection-overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: 이 페이지에서는 NetApp ONTAP 스토리지에 Oracle19c를 배포하는 자동화된 방법을 설명합니다. 
---
= 솔루션 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 페이지에서는 NetApp ONTAP 스토리지에 Oracle19c를 배포하는 자동화된 방법을 설명합니다.



== Oracle 데이터베이스를 위한 자동화된 데이터 보호

조직에서는 효율성을 높이고, 배포를 가속화하고, 수동 작업을 줄이기 위해 환경을 자동화하고 있습니다.  Ansible과 같은 구성 관리 도구는 엔터프라이즈 데이터베이스 운영을 간소화하는 데 사용되고 있습니다.  이 솔루션에서는 NetApp ONTAP 사용하여 Ansible을 사용하여 Oracle의 데이터 보호를 자동화하는 방법을 보여드립니다.  스토리지 관리자, 시스템 관리자, DBA가 오프사이트 데이터 센터나 퍼블릭 클라우드로 일관되고 빠르게 데이터 복제를 설정할 수 있도록 하면 다음과 같은 이점을 얻을 수 있습니다.

* 설계 복잡성과 인적 오류를 제거하고 반복 가능한 일관된 배포 및 모범 사례를 구현합니다.
* Intercluster 복제, CVO 인스턴스화 및 Oracle 데이터베이스 복구 구성 시간 단축
* 데이터베이스 관리자, 시스템 및 스토리지 관리자 생산성 향상
* DR 시나리오를 쉽게 테스트할 수 있도록 데이터베이스 복구 워크플로를 제공합니다.


NetApp 고객에게 검증된 Ansible 모듈과 역할을 제공하여 Oracle 데이터베이스 환경의 배포, 구성 및 수명 주기 관리를 가속화합니다.  이 솔루션은 다음을 수행하는 데 도움이 되는 지침과 Ansible 플레이북 코드를 제공합니다.



=== 온프레미스 간 복제

* 소스와 대상에 클러스터 간 생명선 생성
* 클러스터 및 vserver 피어링 설정
* Oracle 볼륨의 SnapMirror 생성 및 초기화
* AWX/Tower를 통해 Oracle 바이너리, 데이터베이스 및 로그에 대한 복제 일정을 생성합니다.
* 대상에서 Oracle DB를 복원하고 데이터베이스를 온라인 상태로 전환합니다.




=== AWS의 온프레미스에서 CVO로

* AWS 커넥터 생성
* AWS에서 CVO 인스턴스 생성
* Cloud Manager에 온프레미스 클러스터 추가
* 소스에 클러스터 간 생명선 생성
* 클러스터 및 vserver 피어링 설정
* Oracle 볼륨의 SnapMirror 생성 및 초기화
* AWX/Tower를 통해 Oracle 바이너리, 데이터베이스 및 로그에 대한 복제 일정을 생성합니다.
* 대상에서 Oracle DB를 복원하고 데이터베이스를 온라인 상태로 전환합니다.


준비가 되면 클릭하세요link:db-protection-getting-started.html["여기를 클릭하여 솔루션을 시작하세요."] .
